services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8081:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
networks:
  net: