services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: fedora
    volumes:
      - $PWD/aws_backup_script.sh:/tmp/aws_backup_script.sh
    networks:
      - net
  db_host:
    container_name: db
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net
  web: 
    container_name: web
    image: ansible-web
    build:
      context: jenkins-ansible/web
    ports:
      - "80:80"
    networks:
      - net
  # gitlab:
  #   image: gitlab/gitlab-ee:latest
  #   container_name: gitlab_container
  #   restart: always
  #   hostname: 'gitlab.example.com'
  #   ports:
  #     - '8090:80'
  #     - '443:443'
  #     - '22:22'
  #   volumes:
  #     - "$PWD/gitlab_files/config:/etc/gitlab"
  #     - "$PWD/gitlab_files/logs:/var/log/gitlab"
  #     - "$PWD/gitlab_files/data:/var/opt/gitlab"
  #   shm_size: '256m'
  #   networks:
  #     - net

networks:
  net: